baseURL = "https://sinoridha.github.io/ridhar.github.io/"
languageCode = "en-us"
title = "Ridhar's Site"
theme = "hyde"
publishDir= 'docs'
disqusShortname = "ridhar-com"
googleAnalytics = "UA-128028156-1"

[params]
	description = 'Any things that needs to be written'

[menu]
[[menu.main]]
	identifier = "about"
	name = "About"
	title = "About me"
	url = "/about/"
	weight = -110
[[menu.main]]
	identifier = "blog"
	name = "Ridhar Studio"
	title = "Ridhar Studio"
	url = "/ridhar-studio/"
	weight = -100