baseURL: "https://ridhar.com/"
languageCode: "en-us"
title: "Ridha R"
theme: "hyde"
taxonomies:
  tag: tags
Params:
  description: "blogs & thoughts"
publishDir: "docs"
disqusShortname: "ridhar-com"
googleAnalytics: "UA-128028156-1"
menus:
  main:
    - name: "About Me"
      URL: "/about/"
      Weight: 1
    - name: "Ridhar Studio"
      URL: "/ridhar-studio/"
      Weight: 2
