baseURL = "https://ridhar.com"
languageCode = "en-us"
title = "Ridhar's Site"
theme = "hyde"
publishDir= 'docs'

[params]
	description = 'Any things that needs to be written'

[menu]
[[menu.main]]
	identifier = "about"
	name = "About"
	title = "blog section"
	url = "/about/"
	weight = -110
[[menu.main]]
	identifier = "blog"
	name = "Ridhar Studio"
	title = "blog section"
	url = "/ridhar-studio/"
	weight = -100